version: '3.4'

services:
  postgres:
    container_name: lanachallenge_postgres
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 5s
      retries: 10
    restart: always
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
      - ./db/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - "5432:5432"
    networks: 
      lanachallenge_network:
        ipv4_address: 172.21.0.2
  app:
    container_name: lanachallenge_app
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links: 
      - postgres
    tty: true
    networks: 
      lanachallenge_network:
        ipv4_address: 172.21.0.3
    depends_on: 
      - postgres

networks: 
  lanachallenge_network:
    external: true